#!/bin/sh
echo "var GLOBAL_ITEMS = function(){
	var items = [];
	
	for (var key in this)
		items.push(key);
	
	return items;
}();

(function(){" > `dirname "$0"`/Midas.nodejs
cat `dirname "$0"`/*.js >> `dirname "$0"`/Midas.nodejs
echo "})();" >> `dirname "$0"`/Midas.nodejs